"""fixtures table

Revision ID: 1a1deb3ec658
Revises: 
Create Date: 2020-02-01 16:59:59.019995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1deb3ec658'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wikipedia_url', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('team_a', sa.String(length=100), nullable=False),
    sa.Column('team_b', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('competition', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_competition'), 'fixtures', ['competition'], unique=True)
    op.create_index(op.f('ix_fixtures_country'), 'fixtures', ['country'], unique=False)
    op.create_index(op.f('ix_fixtures_date'), 'fixtures', ['date'], unique=False)
    op.create_index(op.f('ix_fixtures_team_a'), 'fixtures', ['team_a'], unique=False)
    op.create_index(op.f('ix_fixtures_team_b'), 'fixtures', ['team_b'], unique=False)
    op.create_index(op.f('ix_fixtures_title'), 'fixtures', ['title'], unique=True)
    op.create_index(op.f('ix_fixtures_wikipedia_url'), 'fixtures', ['wikipedia_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixtures_wikipedia_url'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_title'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_team_b'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_team_a'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_date'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_country'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_competition'), table_name='fixtures')
    op.drop_table('fixtures')
    # ### end Alembic commands ###
