"""competitions are not required to be unique

Revision ID: 225aa5b13868
Revises: 1a1deb3ec658
Create Date: 2020-02-02 14:54:15.330020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225aa5b13868'
down_revision = '1a1deb3ec658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fixtures_competition', table_name='fixtures')
    op.create_index(op.f('ix_fixtures_competition'), 'fixtures', ['competition'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixtures_competition'), table_name='fixtures')
    op.create_index('ix_fixtures_competition', 'fixtures', ['competition'], unique=1)
    # ### end Alembic commands ###
