"""Fixture - is_active column

Revision ID: 499ff9f1cd87
Revises: 272a82bce47d
Create Date: 2020-04-07 11:25:23.976281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499ff9f1cd87'
down_revision = '272a82bce47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
