"""Article subtitle, is_public

Revision ID: db71bca9f5b6
Revises: a0832d72ed6c
Create Date: 2020-06-11 13:13:59.367936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db71bca9f5b6'
down_revision = 'a0832d72ed6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subtitle', sa.String(length=280), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('subtitle')
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
