"""Article edited_timestamp

Revision ID: eb25f3dd26ae
Revises: db71bca9f5b6
Create Date: 2020-06-23 19:03:20.925305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb25f3dd26ae'
down_revision = 'db71bca9f5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_article_edited_timestamp'), ['edited_timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_edited_timestamp'))
        batch_op.drop_column('edited_timestamp')

    # ### end Alembic commands ###
